# Generated by Django 4.1.7 on 2023-09-07 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=120)),
                ('topic', models.CharField(max_length=120)),
                ('nombre_de_questions', models.IntegerField()),
                ('temps', models.IntegerField(help_text='durée du quiz en minutes')),
                ('score_requi_pour_passer', models.IntegerField(help_text='Score en %')),
                ('difficulte', models.CharField(choices=[('facil', 'facil'), ('intermediaire', 'intermediaire'), ('difficil', 'difficil')], max_length=13)),
            ],
        ),
    ]
