# Generated by Django 4.1.7 on 2023-09-07 23:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('monquiz', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='quiz',
            options={'verbose_name_plural': 'Quizes'},
        ),
    ]
